In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os
import numpy as np ;
from keras.utils import np_utils
from keras.layers import Dense,Conv2D,MaxPooling2D,Flatten,Reshape,Dropout
from keras.preprocessing.image import ImageDataGenerator 
from keras.applications.vgg16 import VGG16
from keras.models import Model
import itertools 
import cv2
import pandas as pd ;
import matplotlib.pyplot as plt ;
import tensorflow as tf
from tensorflow.keras.applications import VGG16 , ResNet50 , Xception , InceptionV3
from tensorflow.keras.layers import Flatten
import pandas as pd
import os

# Combining All Features

In [3]:
#Reading from csv files if size is less (less ram consumed)

dataset1 = pd.read_csv("/content/drive/MyDrive/COVID-19/mergedresult.csv")
dataset2 = pd.read_csv("/content/drive/MyDrive/COVID-19/newres.csv")

EmptyDataError: ignored

In [ ]:
#If csv files are huge, divide data in chunks and concat them individually

#Defining paths and chunksize. Chunksize is how many rows will be there in one chunk
path1="/content/drive/MyDrive/covid-19/xceptionoutput.csv"
path2="/content/drive/MyDrive/covid-19/resnet50.csv"
chunksize = 50

#Getting dataset1 via chunk method
tfr1 = pd.read_csv(path1, chunksize=chunksize, iterator=True,header= None)
dataset1 =[]
dataset1 = pd.DataFrame(dataset1)
i=1
with tfr1 as reader:
    for chunk in reader:
        print("index_value")
        print(i)
        dataset1 = pd.concat([dataset1,chunk], axis=0, ignore_index=True)
        i=i+1

index_value
1
index_value
2
index_value
3
index_value
4
index_value
5
index_value
6
index_value
7
index_value
8
index_value
9
index_value
10
index_value
11
index_value
12
index_value
13
index_value
14
index_value
15
index_value
16
index_value
17
index_value
18
index_value
19
index_value
20
index_value
21
index_value
22
index_value
23
index_value
24
index_value
25
index_value
26
index_value
27
index_value
28
index_value
29
index_value
30
index_value
31
index_value
32
index_value
33
index_value
34
index_value
35
index_value
36
index_value
37
index_value
38
index_value
39
index_value
40
index_value
41
index_value
42
index_value
43
index_value
44
index_value
45
index_value
46
index_value
47
index_value
48
index_value
49
index_value
50
index_value
51
index_value
52
index_value
53
index_value
54
index_value
55
index_value
56
index_value
57
index_value
58
index_value
59
index_value
60
index_value
61
index_value
62
index_value
63
index_value
64
index_value
65
index_value
66
index_value
67
index_value
68
index_value
69
index_value
70
index_value
71
index_value
72
index_value
73
index_value
74
index_value
75
index_value
76
index_value
77
index_value
78
index_value
79
index_value
80
index_value
81
index_value
82
index_value
83
index_value
84
index_value
85
index_value
86
index_value
87
index_value
88
index_value
89
index_value
90
index_value
91
index_value
92
index_value
93
index_value
94
index_value
95
index_value
96
index_value
97

In [ ]:
#Getting dataset2 via chunk method
chunksize = 5

tfr2 = pd.read_csv(path2, chunksize=chunksize, iterator=True,header= None)
dataset2=[]
dataset2= pd.DataFrame(dataset2)
i=1
with tfr2 as reader:
    for chunk in reader:
        print("index_value")
        print(i)
        dataset2 = pd.concat([dataset2,chunk], axis=0, ignore_index=True)
        i=i+1

index_value
1
index_value
2
index_value
3
index_value
4
index_value
5
index_value
6
index_value
7
index_value
8
index_value
9
index_value
10
index_value
11
index_value
12
index_value
13
index_value
14
index_value
15
index_value
16
index_value
17
index_value
18
index_value
19
index_value
20
index_value
21
index_value
22
index_value
23
index_value
24
index_value
25
index_value
26
index_value
27
index_value
28
index_value
29
index_value
30
index_value
31
index_value
32
index_value
33
index_value
34
index_value
35
index_value
36
index_value
37
index_value
38
index_value
39
index_value
40
index_value
41
index_value
42
index_value
43
index_value
44
index_value
45
index_value
46
index_value
47
index_value
48
index_value
49
index_value
50
index_value
51
index_value
52
index_value
53
index_value
54
index_value
55
index_value
56
index_value
57
index_value
58
index_value
59
index_value
60
index_value
61
index_value
62
index_value
63
index_value
64
index_value
65
index_value
66
index_value
67
index_value
68
index_value
69
index_value
70
index_value
71
index_value
72
index_value
73
index_value
74
index_value
75
index_value
76
index_value
77
index_value
78
index_value
79
index_value
80
index_value
81
index_value
82
index_value
83
index_value
84
index_value
85
index_value
86
index_value
87
index_value
88
index_value
89
index_value
90
index_value
91
index_value
92
index_value
93
index_value
94
index_value
95
index_value
96
index_value
97
index_value
98
index_value
99
index_value
100
index_value
101
index_value
102
index_value
103
index_value
104
index_value
105
index_value
106
index_value
107
index_value
108
index_value
109
index_value
110
index_value
111
index_value
112
index_value
113
index_value
114
index_value
115
index_value
116
index_value
117
index_value
118
index_value
119
index_value
120
index_value
121
index_value
122
index_value
123
index_value
124
index_value
125
index_value
126
index_value
127
index_value
128
index_value
129
index_value
130
index_value
131
index_value
132
index_value
133
index_value
134
index_value
135
index_value
136
index_value
137
index_value
138
index_value
139
index_value
140
index_value
141
index_value
142
index_value
143
index_value
144
index_value
145
index_value
146
index_value
147
index_value
148
index_value
149
index_value
150
index_value
151
index_value
152
index_value
153
index_value
154
index_value
155
index_value
156
index_value
157
index_value
158
index_value
159
index_value
160
index_value
161
index_value
162
index_value
163
index_value
164
index_value
165
index_value
166
index_value
167
index_value
168
index_value
169
index_value
170
index_value
171
index_value
172
index_value
173
index_value
174
index_value
175
index_value
176
index_value
177
index_value
178
index_value
179
index_value
180
index_value
181
index_value
182
index_value
183
index_value
184
index_value
185
index_value
186
index_value
187
index_value
188
index_value
189
index_value
190
index_value
191
index_value
192
index_value
193
index_value
194
index_value
195
index_value
196
index_value
197
index_value
198
index_value
199
index_value
200
index_value
201
index_value
202
index_value
203
index_value
204
index_value
205
index_value
206
index_value
207
index_value
208
index_value
209
index_value
210
index_value
211
index_value
212
index_value
213
index_value
214
index_value
215
index_value
216
index_value
217
index_value
218
index_value
219
index_value
220
index_value
221
index_value
222
index_value
223
index_value
224
index_value
225
index_value
226
index_value
227
index_value
228
index_value
229
index_value
230
index_value
231
index_value
232
index_value
233
index_value
234
index_value
235
index_value
236
index_value
237
index_value
238
index_value
239
index_value
240
index_value
241
index_value
242
index_value
243
index_value
244
index_value
245
index_value
246
index_value
247
index_value
248
index_value
249
index_value
250
index_value
251
index_value
252
index_value
253
index_value
254
index_value
255
index_value
256
index_value
257
index_value
258
index_value
259
index_value
260
index_value
261
index_value
262
index_value
263
index_value
264
index_value
265
index_value
266
index_value
267
index_value
268
index_value
269
index_value
270
index_value
271
index_value
272
index_value
273
index_value
274
index_value
275
index_value
276
index_value
277
index_value
278
index_value
279
index_value
280
index_value
281
index_value
282
index_value
283
index_value
284
index_value
285
index_value
286
index_value
287
index_value
288
index_value
289
index_value
290
index_value
291
index_value
292
index_value
293
index_value
294
index_value
295
index_value
296
index_value
297
index_value
298
index_value
299
index_value
300
index_value
301
index_value
302
index_value
303
index_value
304
index_value
305
index_value
306
index_value
307
index_value
308
index_value
309
index_value
310
index_value
311
index_value
312
index_value
313
index_value
314
index_value
315
index_value
316

In [ ]:
#visualize dataset1
dataset1

,0,1,2,3,4,5,6,7,8,9,...,100344,100345,100346,100347,100348,100349,100350,100351,100352,100353
0,0,Covid (1)aug1.png,0.0,0.000000,0.000000,0.0,0.0,0.0,8.229795,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,Covid (1)aug2.png,0.0,2.631366,0.000000,0.0,0.0,0.0,1.994376,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0,Covid (1)aug3.png,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0,Covid (10)aug2.png,0.0,13.618897,9.224132,0.0,0.0,0.0,0.119662,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0,Covid (10)aug3.png,0.0,0.000000,0.000000,0.0,0.0,0.0,2.676702,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
743,1,Non-Covid (98)aug1.png,0.0,0.000000,0.000000,0.0,0.0,0.0,27.391451,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
744,1,Non-Covid (98)aug2.png,0.0,5.874099,0.000000,0.0,0.0,0.0,15.751949,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
745,1,Non-Covid (99)aug1.png,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
746,1,Non-Covid (99)aug2.png,0.0,7.718884,12.332410,0.0,0.0,0.0,11.227491,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
747,1,Non-Covid (99)aug3.png,0.0,0.000000,0.000000,0.0,0.0,0.0,1.741211,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
#visualize dataset2
dataset2

,0,1,2,3,4,5,6,7,8,9,...,51192,51193,51194,51195,51196,51197,51198,51199,51200,51201
0,0,Covid (1)aug1.png,33.330696,0.000000,0.0,40.932056,92.810440,24.793255,0.000000,9.720383,...,154.433731,0.000000,14.726862,0.0,39.420868,0.0,67.805923,0.0,0.0,12.911546
1,0,Covid (1)aug2.png,0.000000,0.000000,0.0,0.000000,27.364887,15.128222,0.000000,46.428265,...,165.065338,0.000000,104.484314,0.0,0.000000,0.0,16.991598,0.0,0.0,24.733683
2,0,Covid (1)aug3.png,40.560368,0.134959,0.0,34.271881,0.000000,56.492798,2.885268,89.530495,...,51.142761,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
3,0,Covid (10)aug2.png,0.000000,0.000000,0.0,21.399273,0.000000,0.000000,0.000000,64.756027,...,10.910521,23.275793,68.550674,0.0,0.000000,0.0,7.431638,0.0,0.0,0.000000
4,0,Covid (10)aug3.png,38.940289,0.000000,0.0,31.829910,21.701748,45.132950,0.000000,20.122356,...,0.000000,0.000000,0.000000,0.0,42.770382,0.0,22.950132,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
743,1,Non-Covid (98)aug1.png,39.168209,0.000000,0.0,24.297890,44.743034,70.756310,0.000000,18.624022,...,130.115402,0.000000,1.272250,0.0,0.000000,0.0,48.576035,0.0,0.0,0.000000
744,1,Non-Covid (98)aug2.png,23.322788,0.000000,0.0,15.349975,0.000000,45.636627,0.000000,0.000000,...,222.206635,0.000000,156.540848,0.0,0.000000,0.0,71.589020,0.0,0.0,12.509047
745,1,Non-Covid (99)aug1.png,51.071392,0.000000,0.0,29.171589,63.242615,89.159004,0.000000,32.123974,...,157.503098,12.325460,0.000000,0.0,0.000000,0.0,139.048157,0.0,0.0,0.000000
746,1,Non-Covid (99)aug2.png,0.000000,0.000000,0.0,47.562931,0.000000,44.598698,0.000000,58.067295,...,112.077148,54.466068,53.790749,0.0,0.000000,0.0,3.885099,0.0,0.0,0.000000
747,1,Non-Covid (99)aug3.png,67.192482,11.361485,0.0,48.596535,17.348459,120.545952,0.959682,98.422935,...,69.481712,0.000000,0.000000,0.0,7.090436,0.0,62.831303,0.0,0.0,0.000000

In [ ]:
#Optional Code. Run this if any of the two datasets have one extra row in the beginning due to not using header=None while saving the dataset
dataset1.drop(index=dataset1.index[0], 
        axis=0, 
        inplace=True)

In [ ]:
#merge dataset2 on the right of dataset 1 while taking dataset2.iloc[:,1] i.e 2nd column as key. 
#2nd colum contains name of files which is common in both datasets and combines rows with same file name 
df = dataset1.merge(dataset2, left_on=dataset2.columns[1], right_on=dataset2.columns[1], how='left')

#visualize the dataframe
df

,0_x,1,2_x,3_x,4_x,5_x,6_x,7_x,8_x,9_x,...,51192_y,51193_y,51194_y,51195_y,51196_y,51197_y,51198_y,51199_y,51200_y,51201_y
0,0,Covid (1)aug2.png,0.0,2.631366,0.000000,0.0,0.0,0.0,1.994376,0.0,...,165.065338,0.000000,104.484314,0.0,0.000000,0.0,16.991598,0.0,0.0,24.733683
1,0,Covid (1)aug3.png,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,...,51.142761,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
2,0,Covid (10)aug2.png,0.0,13.618897,9.224132,0.0,0.0,0.0,0.119662,0.0,...,10.910521,23.275793,68.550674,0.0,0.000000,0.0,7.431638,0.0,0.0,0.000000
3,0,Covid (10)aug3.png,0.0,0.000000,0.000000,0.0,0.0,0.0,2.676702,0.0,...,0.000000,0.000000,0.000000,0.0,42.770382,0.0,22.950132,0.0,0.0,0.000000
4,0,Covid (100)aug1.png,0.0,1.339336,0.000000,0.0,0.0,0.0,8.450649,0.0,...,120.954002,0.000000,13.757668,0.0,8.053288,0.0,37.803932,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,1,Non-Covid (98)aug1.png,0.0,0.000000,0.000000,0.0,0.0,0.0,27.391451,0.0,...,130.115402,0.000000,1.272250,0.0,0.000000,0.0,48.576035,0.0,0.0,0.000000
743,1,Non-Covid (98)aug2.png,0.0,5.874099,0.000000,0.0,0.0,0.0,15.751949,0.0,...,222.206635,0.000000,156.540848,0.0,0.000000,0.0,71.589020,0.0,0.0,12.509047
744,1,Non-Covid (99)aug1.png,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,...,157.503098,12.325460,0.000000,0.0,0.000000,0.0,139.048157,0.0,0.0,0.000000
745,1,Non-Covid (99)aug2.png,0.0,7.718884,12.332410,0.0,0.0,0.0,11.227491,0.0,...,112.077148,54.466068,53.790749,0.0,0.000000,0.0,3.885099,0.0,0.0,0.000000
746,1,Non-Covid (99)aug3.png,0.0,0.000000,0.000000,0.0,0.0,0.0,1.741211,0.0,...,69.481712,0.000000,0.000000,0.0,7.090436,0.0,62.831303,0.0,0.0,0.000000

In [ ]:
# check where are extra values in this new combined dataset df. 
# for example if dataset1 had 10,000 columns then dataset2 is added.
# then dataset2 also has 2 extra columns i.e label and file names. 
# these need to be deleted since dataset1 already has them covered.

#To check this, start with columns where dataset1 ends.
# Example: if dataset1 had 10000 columns then dataset2 is added,
# then in combined dataset df, values from 9999th to 10005th may have extra values

#check for them like this

df.iloc[:,[0,1,100351,100352,100353,100354,100355,100356,100357,100358]]

,0_x,1,100351,100352,100353,0_y,2_y,3_y,4_y,5_y
0,0,Covid (1)aug2.png,0.0,0.0,0.0,0,0.000000,0.000000,0.0,0.000000
1,0,Covid (1)aug3.png,0.0,0.0,0.0,0,40.560368,0.134959,0.0,34.271881
2,0,Covid (10)aug2.png,0.0,0.0,0.0,0,0.000000,0.000000,0.0,21.399273
3,0,Covid (10)aug3.png,0.0,0.0,0.0,0,38.940289,0.000000,0.0,31.829910
4,0,Covid (100)aug1.png,0.0,0.0,0.0,0,12.576550,0.000000,0.0,5.474581
...,...,...,...,...,...,...,...,...,...,...
742,1,Non-Covid (98)aug1.png,0.0,0.0,0.0,1,39.168209,0.000000,0.0,24.297890
743,1,Non-Covid (98)aug2.png,0.0,0.0,0.0,1,23.322788,0.000000,0.0,15.349975
744,1,Non-Covid (99)aug1.png,0.0,0.0,0.0,1,51.071392,0.000000,0.0,29.171589
745,1,Non-Covid (99)aug2.png,0.0,0.0,0.0,1,0.000000,0.000000,0.0,47.562931
746,1,Non-Covid (99)aug3.png,0.0,0.0,0.0,1,67.192482,11.361485,0.0,48.596535

In [ ]:
#after finding those two extra columns, drop them. 
#also drop first column(this is extra column created by merge funtion)
df =df.drop(df.columns[[1,100353]],
                       axis = 1)
#column names are not 0,1,2,3,4,5... they are 0x,1x,2x etc etc. 
#therefore these two lines change it
df = df[:].values
df=pd.DataFrame(df)

In [ ]:
#now updated dataset looks like this with first column as label/output, 2nd column as file name
# and rest of columns are combined features
df

,0,1,2,3,4,5,6,7,8,9,...,151543,151544,151545,151546,151547,151548,151549,151550,151551,151552
0,0.0,0.0,2.631366,0.000000,0.0,0.0,0.0,1.994376,0.0,0.00000,...,165.065338,0.000000,104.484314,0.0,0.000000,0.0,16.991598,0.0,0.0,24.733683
1,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.00000,...,51.142761,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
2,0.0,0.0,13.618897,9.224132,0.0,0.0,0.0,0.119662,0.0,0.00000,...,10.910521,23.275793,68.550674,0.0,0.000000,0.0,7.431638,0.0,0.0,0.000000
3,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,2.676702,0.0,0.00000,...,0.000000,0.000000,0.000000,0.0,42.770382,0.0,22.950132,0.0,0.0,0.000000
4,0.0,0.0,1.339336,0.000000,0.0,0.0,0.0,8.450649,0.0,2.29658,...,120.954002,0.000000,13.757668,0.0,8.053288,0.0,37.803932,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,1.0,0.0,0.000000,0.000000,0.0,0.0,0.0,27.391451,0.0,0.00000,...,130.115402,0.000000,1.272250,0.0,0.000000,0.0,48.576035,0.0,0.0,0.000000
743,1.0,0.0,5.874099,0.000000,0.0,0.0,0.0,15.751949,0.0,0.00000,...,222.206635,0.000000,156.540848,0.0,0.000000,0.0,71.589020,0.0,0.0,12.509047
744,1.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.00000,...,157.503098,12.325460,0.000000,0.0,0.000000,0.0,139.048157,0.0,0.0,0.000000
745,1.0,0.0,7.718884,12.332410,0.0,0.0,0.0,11.227491,0.0,0.00000,...,112.077148,54.466068,53.790749,0.0,0.000000,0.0,3.885099,0.0,0.0,0.000000
746,1.0,0.0,0.000000,0.000000,0.0,0.0,0.0,1.741211,0.0,0.00000,...,69.481712,0.000000,0.000000,0.0,7.090436,0.0,62.831303,0.0,0.0,0.000000

In [ ]:
#optional code, see if an extra header row is added at top. if yes then remove it else ignore this code
df.drop(index=df.index[0], 
        axis=0, 
        inplace=True)

In [ ]:
#save your project
df.to_csv("/content/drive/MyDrive/mergedresult.csv", index= False, header= None)